---
title: "Investigating the Effects of Marijuana Legalization"
---

<br>

### Project Purpose
The premise of this project is to look at how the legalization of marijuana has affected the use of other substances, such as illicit drugs, alcohol and cigarettes. The dataset being utilized comes from The National Survey on Drug Use and Health (NSDUH), which measures the prevalence and correlates of drug use in the United States both quarterly and annually. Furthermore, to investigate potential differences in states that have legalized marijuana from the period prior to legalization and after, through time-series graphs. Another important comparison to make would be between states that have legalized marijuana and those that haven't to better understand any potential changes in substance use due to legalization.

A short synopsis and how to navigate our project is included below. For more details on the making of this project, please visit our [project repository on Github](https://github.com/kblitsman/p8105_final).

<iframe width="560" height="315" src="https://www.youtube.com/embed/H3WLtdV1bXY" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

<br>

### Data
To examine marijuana and other substance use, we used the [National Survey on Drug Use and Health (NSDUH)](https://nsduhweb.rti.org/respweb/homepage.cfm). The NSDUH contains data on various tobacco, alcohol, and other substance use while also containing some basic demographic information such as age and state of residence. The [dataset](https://datafiles.samhsa.gov/study/national-survey-drug-use-and-health-nsduh-2015-nid16893) that was utilized contained data from 1999 to 2015, which unfortunately does not provide a large amount of data for examining Washington and Colorado's 2012 legalization of marijuana for recreational use. Additional states have also approved the use of recreational marijuana, bringing the total number to eight, while there are 29 states and the District of Columbia that have approved of medical marijuana use. 

<br>

### Analysis
We initially decided to create an interactive shiny graph to allow for examination of state counts of substance use over the past years. By creating a time-series graph for a selected state, a user will be able to visualize the overall trend for a specific substance across the ten year time period. Users can view this across various age groups or for all age groups combined to view potential differences by age and by state. This provided us with the opportunity to assess the estimated count of substance users in states with various policies regarding marijuana and other substances, which can help to inform us as to the true effects of marijuana legalization.

<br>
We then decided that we would like to implement an easy way to compare the amount of substance users within states to other states. In order to do this, we created a proportion measure for users to total population to ensure an appropriate comparison. Then, we created a clustered bar chart displaying the relationship between year and proportion of substance user for two selected states. This allows quick between state comparisons, which can help us to understand how marijuana legalization has effected other substance use.

<br>
You can interact with our graphs and compare the rates of substance use [here](https://kblitsman.shinyapps.io/p8105_final_shiny/), while our investigation and conclusions regarding the data can be found [here](results.html).

<br>

### Timeline of when marijuana use was approved by voters  
The timeline below allows you to scroll through and see what states have approved recreational or medical marijuana use and when that occurred.  
```{r timeline, echo=FALSE}
library(timevis)

# Election date that it was legalized for medical or recreational use
timevis(data = data.frame(
start = c("2012-11-06", "2012-11-06", "2014-11-04", "2014-11-04",
          "2016-11-08", "2016-11-08", "2016-11-08", "2016-11-08",
          "1996-11-05", "1998-11-03", "1998-11-03", "1998-11-03",
          "1999-11-02", "2000-11-07", "2000-11-07", "2000-11-07",
          "2004-11-02", "2004-11-02", "2006-11-07", "2007-11-06",
          "2008-11-04", "2010-11-02", "2010-11-02", "2010-11-02",
          "2011-11-08", "2012-11-06", "2012-11-06", "2013-11-05",
          "2013-11-05", "2014-11-04", "2014-11-04", "2014-11-04",
          "2015-11-03", "2016-11-08", "2016-11-08", "2016-11-08",
          "2016-11-08", "2016-11-08"),
content = c("Colorado", "Washington","Oregon", "Alaska", 
            "Nevada", "California", "Maine", "Massachusetts",
            "California", "Alaska", "Oregon", "Washington",
            "Maine", "Colorado", "Hawaii", "Nevada",
            "Montana", "Vermont", "Rhode Island", "New Mexico",
            "Michigan", "Arizona", "D.C.", "New Jersey",
            "Deleware", "Connecticut", "Massachusettes", "Illinois",
            "New Hampshire", "Maryland", "Minnesota", "New York",
            "Louisiana", "Ohio", "Pennsylvania", "Florida",
            "North Dakota", "Arkansas"),
group = c(1, 1, 1, 1, 1, 1, 1, 1,
          2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2)),
groups = data.frame(id = 1:2, content = c("Recreational", "Medical"))
) %>%
setGroups(data.frame(id = 1:2, content = c("Recreational", "Medical")))

```




