---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
library(janitor)
library(forcats)
library(stringr)
library(broom)
library(tidytext)
library(haven)
<<<<<<< HEAD
library(shiny)
library(plotly)
library(viridis)
=======
library(plotly)
>>>>>>> c9cd0cc1384177ad5f7bf21dba07e3b0ad9f8c1a
```

# Importing Data

```{r import}
saes = read_sas("./state_saes_final.sas7bdat") %>%
  clean_names() %>% 
  filter(pyear > 4 & pyear != 12 & area == 2) %>% 
  select(outname, pyearnm, area, stname, pyear, agegrp, est_total, nsel, ncomp, pop) %>% 
  mutate(agegrp = ifelse(agegrp == 0, "12 or older",
                         ifelse(agegrp == 1, "12 to 17",
                         ifelse(agegrp == 2, "18 to 25",
                         ifelse(agegrp == 3, "26 or older",
                         ifelse(agegrp == 4, "18 or older",
                         ifelse(agegrp == 5, "12 to 20", NA)))))))
```

## Including Plots

```{r plots, echo=FALSE}
<<<<<<< HEAD
# selectInput widget: State
states = saes %>% distinct(stname) %>% pull()
selectInput("state_choice", label = h3("Select state"),
            choices = states, selected = "Colorado")
renderPrint({ 
  input$state_choice
})

# selectInput widget: outcome
outcomes = saes %>% distinct(outname) %>% pull()
selectInput("outcome_choice", label = h3("Select outcome"),
            choices = outcomes, selected = "marijuana use in the past year")
renderPrint({ 
  input$outcome_choice
})

# radioButtons widget: age group
age_group = saes %>% distinct(agegrp) %>% pull()
radioButtons("age_group", label = h3("Choose age group"),
    choices = age_group, 
    selected = "18 or older")
renderPrint({ 
  input$age_group
})

Renderplotly({
  saes %>% 
    filter(outname == "marijuana use in the past year",
           agegrp == "18 or older",
           stname == "Colorado") %>% 
    plot_ly(x = ~pyearnm, y = ~est_total, type = "scatter", mode = "markers",
          alpha = 0.5)
})

ggplot(aes(x = pyearnm, y = est_total)) +
=======
saes %>% 
    filter(outname == "nonmedical use of pain relievers in the past year" & agegrp == 0 & stname == "Colorado") %>% 
    mutate(pyearnm = ifelse(pyearnm == "2010-2011 (published)", "2010-2011", pyearnm)) %>%
    ggplot(aes(x = pyearnm, y = est_total)) +
>>>>>>> c9cd0cc1384177ad5f7bf21dba07e3b0ad9f8c1a
    geom_point() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```


```{r Map}
library(plotly)
df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2011_us_ag_exports.csv")
df$hover <- with(df, paste(state, '<br>', "Beef", beef, "Dairy", dairy, "<br>",
                           "Fruits", total.fruits, "Veggies", total.veggies,
                           "<br>", "Wheat", wheat, "Corn", corn))
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

p <- plot_geo(df, locationmode = 'USA-states') %>%
  add_trace(
    z = ~total.exports, text = ~hover, locations = ~code,
    color = ~total.exports, colors = 'Purples'
  ) %>%
  colorbar(title = "Millions USD") %>%
  layout(
    title = '2011 US Agriculture Exports by State<br>(Hover for breakdown)',
    geo = g
  )
p
# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
chart_link = plotly_POST(p, filename="choropleth/ag")
chart_link
```
