---
title: "Investigating the Effect of Marijuana Legalization on Alternate Substance Use
" 
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}

# Loading packages 
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(haven)
library(janitor)
library(shiny)
library(viridis)

# Bringing in the data and variables we need, defining our age groups and outcome variables.   
saes = read_sas("./state_saes_final.sas7bdat") %>%
  clean_names() %>% 
  filter(pyear > 4 & pyear != 12 & area == 2) %>% 
  select(outname, pyearnm, area, stname, pyear, agegrp, est_total, nsel, ncomp, pop) %>% 
  mutate(agegrp = ifelse(agegrp == 0, "All",
                         ifelse(agegrp == 1, "12 to 17",
                         ifelse(agegrp == 2, "18 to 25",
                         ifelse(agegrp == 4, "26 or older", NA))))) %>% 
  filter(!is.na(agegrp),
         outname %in% c("alcohol use in the past month", 
                        "binge alcohol use in the past month",
                      "illicit drug use other than marijuana in the past month",
                      "cigarette use in the past month",
                      "tobacco use in the past month",
                      "marijuana use in the past month"
                      )) 
saes$pyearnm = as.factor(saes$pyearnm)
levels(saes$pyearnm) = gsub("-", "\n", levels(saes$pyearnm))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r widgets, echo=FALSE}
# selectInput widget: Initial state
states = saes %>% distinct(stname) %>% pull()
selectInput("first_state", label = h3("Select state"),
            choices = states, selected = "Colorado")

# selectInput widget: Comaprison state
selectInput("second_state", label = h3("Select comparison state"),
            choices = states, selected = "Washington")

# selectInput widget: Outcome variable 
outcomes = saes %>% distinct(outname) %>% pull()
selectInput("outcome_choice", label = h3("Select outcome"),
            choices = outcomes, selected = "marijuana use in the past month")

# radioButtons widget: Age group
age_group = saes %>% distinct(agegrp) %>% pull()
radioButtons("age_group", label = h3("Choose age group"),
    choices = age_group, 
    selected = "All")

# selectInput widet: year
years = saes %>% distinct(pyearnm) %>% pull()
selectInput("year_range", label = h3("Choose year"), 
            choices = years, selected = "2010")

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Time-series graph

```{r create_timegraph}
# By creating a time-series graph for a selected state, a user will be able to visualize the overall trend for a specific substance across the ten year time period. Users can view this across various age groups or with the entire population. 

saes$hover <- with(saes, paste(pyearnm, '<br>', "Total count (Thousands):", est_total))

renderPlotly({
  saes %>% 
    filter(outname == input$outcome_choice,
           agegrp == input$age_group,
           stname == input$first_state) %>% 
    plot_ly(x = ~pyearnm, y = ~est_total, type = "scatter", mode = "lines+markers", hoverinfo = 'text', text = ~paste(pyearnm, '<br>', "Total count:", est_total),
          marker = list(size = 10,
                       color = 'rgba(255, 182, 193, .9)',
                       line = list(color = 'rgba(152, 0, 0, .8)',
                                   width = 2))) %>%
  layout(title = input$outcomechoice,
         yaxis = list(zeroline = TRUE, title = "Estimated average number of persons (in thousands)"),
         xaxis = list(zeroline = TRUE, title = "Year Range"),
         margin = list(b = 100), xaxis = list(tickprefix = " "))
})
```

-----------------------------------------------------------------------

### Comparison Graph

```{r create_compgraph}
# The comparison will allow a user to compare the overall numbers of users for a specific substance by year and also to view overall trends across the time period. Users can view this across various age groups or with the entire population.  

renderPlotly({
p = saes %>%
  filter(stname %in% c(input$first_state, input$second_state), agegrp == input$age_group, outname == input$outcome_choice) %>%
  ggplot(aes(x = pyearnm, fill = stname)) +
  geom_bar(aes(group = stname, y = est_total*1000/pop*100), position = position_dodge(width = 0.6), stat = "identity") + labs(
    title = "Comparing Monthly Substance Users Between States",
    x = "Years",
    y = "Proportion Users to Population (%)",
    fill = "States Compared:"
  ) + 
  theme_bw() +
  theme(axis.title.x = element_blank());

ggplotly(p, tooltip = c('fill', 'x', 'y'))
})
```

-----------------------------------------------------------------------

### Scatter Graph

```{r create_scatter}
# 
renderPlotly({
saes %>%
  filter(agegrp == input$age_group, outname == input$outcome_choice) %>%
  plot_ly(
  x = ~pop, y = ~est_total*1000,
  # Hover text:
  hoverinfo = 'text',
  text = ~paste("State:", stname, '<br>Total Users:', est_total*1000, '<br>Population:', pop),
  color = ~est_total, size = ~est_total
)
})
```



