---
title: "Final Project - Comparison" 
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(haven)
library(janitor)
library(shiny)
library(viridis)

saes = read_sas("./state_saes_final.sas7bdat") %>%
  clean_names() %>% 
  filter(pyear > 4 & pyear != 12 & area == 2) %>% 
  select(outname, pyearnm, area, stname, pyear, agegrp, est_total, nsel, ncomp, pop) %>% 
  mutate(agegrp = ifelse(agegrp == 0, "All",
                         ifelse(agegrp == 1, "12 to 17",
                         ifelse(agegrp == 2, "18 to 25",
                         ifelse(agegrp == 3, "26 or older", NA))))) %>%
  filter(!is.na(agegrp),
         outname %in% c("alcohol use in the past month", 
                      "illicit drug use other than marijuana in the past month",
                      "cigarette use in the past month",
                      "marijuana use in the past month"
                      ))
saes$pyearnm = as.factor(saes$pyearnm)
levels(saes$pyearnm) = gsub("-", "\n", levels(saes$pyearnm))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r widgets, echo=FALSE}
# selectInput widget: State 1
states = saes %>% distinct(stname) %>% pull()
selectInput("first_state", label = h3("Select initial state"),
            choices = states, selected = "Colorado")


# selectInput widget: State 2
selectInput("second_state", label = h3("Select comparison state"),
            choices = states, selected = "Washington")


# selectInput widget: outcome
outcomes = saes %>% distinct(outname) %>% pull()
selectInput("outcome_choice", label = h3("Select outcome"),
            choices = outcomes, selected = "marijuana use in the past month")


# radioButtons widget: age group
age_group = saes %>% distinct(agegrp) %>% pull()
radioButtons("age_group", label = h3("Choose age group"),
    choices = age_group, 
    selected = "All")



```


Row
-----------------------------------------------------------------------

### Comparison Graph

```{r}

renderPlotly({
p = saes %>%
  filter(stname %in% c(input$first_state, input$second_state), agegrp == input$age_group, outname == input$outcome_choice) %>%
  ggplot(aes(x = pyearnm, fill = stname)) +
  geom_bar(aes(group = stname, y = est_total*1000/pop*100), position = position_dodge(width=0.6), stat="identity") + labs(
    title = "Comparing Monthly Substance Users in States",
    x = "Years",
    y = "Proportion Users to Population (%)",
    fill = "States Compared:"
  ) + 
  theme_bw() +
  theme(axis.title.x = element_blank());

ggplotly(p, tooltip = c('fill', 'x', 'y'))
})
```

