---
title: "Investigating the Effect of Marijuana Legalization on Alternate Substance Use" 
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}
# The premise of this project is to look at how the legalization of marijuana has affected the use of other substances, such as illicit drugs, alcohol and cigarettes. The dataset being utilized comes from The National Survey on Drug Use and Health (NSDUH), which measures the prevalence and correlates of drug use in the United States both quarterly and annually. Furthermore, to investigate potential differences in states that have legalized marijuana from the period prior to legalization and after, through time-series graphs. Another important comparison to make would be between states that have legalized marijuana and those that haven't to better understand any potential changes in substance use due to legalization.


# Loading packages 
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(stringr)
library(ggplot2)
library(haven)
library(janitor)
library(shiny)
library(viridis)

# Bringing in the data and variables we need, defining our age groups and outcome variables.   
saes = read_sas("./state_saes_final.sas7bdat") %>%
  clean_names() %>% 
  filter(pyear > 4 & pyear != 12 & area == 2) %>% 
  select(outname, pyearnm, area, stname, pyear, agegrp, est_total, nsel, ncomp, pop) %>% 
  mutate(agegrp = ifelse(agegrp == 0, "All",
                         ifelse(agegrp == 1, "12 to 17",
                         ifelse(agegrp == 2, "18 to 25",
                         ifelse(agegrp == 4, "26 or older", NA))))) %>% 
  filter(!is.na(agegrp),
         outname %in% c("alcohol use in the past month", 
                        "binge alcohol use in the past month",
                      "illicit drug use other than marijuana in the past month",
                      "cigarette use in the past month",
                      "tobacco use in the past month",
                      "marijuana use in the past month"
                      )) 
saes$pyearnm = as.factor(saes$pyearnm)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r widgets, echo=FALSE}
# selectInput widget: Initial state
states = saes %>% distinct(stname) %>% pull()
selectInput("first_state", label = h3("Select state"),
            choices = states, selected = "Colorado")

# selectInput widget: Comaprison state
selectInput("second_state", label = h3("Select comparison state (for comparison graph)"),
            choices = states, selected = "Washington")

# selectInput widget: Outcome variable 
outcomes = saes %>% distinct(outname) %>% pull()
selectInput("outcome_choice", label = h3("Select outcome"),
            choices = outcomes, selected = "marijuana use in the past month")

# radioButtons widget: Age group
age_group = saes %>% distinct(agegrp) %>% pull()
radioButtons("age_group", label = h3("Choose age group"),
    choices = age_group, 
    selected = "All")

# selectInput widet: year
years = saes %>% distinct(pyearnm) %>% pull()
selectInput("year_range", label = h3("Choose year (for scatter graph)"), 
            choices = years, selected = "2010")

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Time-series graph

```{r create_timegraph}
# By creating a time-series graph for a selected state, a user will be able to visualize the overall trend for a specific substance across the ten year time period. Users can view this across various age groups or for all age groups combined to view potential differences by age and by state.

# Creating count of estimated users by year using plotly
renderPlotly({
  saes %>% 
    filter(outname == input$outcome_choice,
           agegrp == input$age_group,
           stname == input$first_state) %>% 
    plot_ly(x = ~pyearnm, y = ~est_total, type = "scatter", mode = "lines+markers", hoverinfo = 'text', text = ~paste("Year:", pyearnm, '<br>', "Total count:", est_total),
          marker = list(size = 10,
                       color = 'rgba(255, 182, 193, .9)',
                       line = list(color = 'rgba(152, 0, 0, .8)',
                                   width = 2))) %>%
  layout(title = input$outcomechoice,
         yaxis = list(zeroline = TRUE, title = "Estimated Total Number of Users (in thousands)"),
         xaxis = list(zeroline = TRUE, title = "Year Range"),
         margin = list(b = 100), xaxis = list(tickprefix = " "))
})
```

-----------------------------------------------------------------------

### Comparison Graph

```{r create_compgraph}
# The comparison graph will allow a user to compare the overall proportion of substance users in a state for a specific substance by year and also to view overall trends across the time period. Users can view this across various age groups or for all age groups combined to view potential differences by age and by state. The graph will also allow users to look at one state solely without a comparison.   

# Creating comparison graph in ggplot and then bringing it into plotly using ggplotly
renderPlotly({
  levels(saes$pyearnm) = gsub("-", "\n", levels(saes$pyearnm))
p = saes %>%
  filter(stname %in% c(input$first_state, input$second_state), 
         agegrp == input$age_group, 
         outname == input$outcome_choice) %>%
  ggplot(aes(x = pyearnm, y = est_total*1000/pop*100, fill = stname, text = paste('State:', stname, '</br></br>Year:', substring(pyearnm,1,4), '</br>Proportion Users:', round(est_total*1000/pop*100,2), "%"))) +
  geom_bar(colour = "black", position = position_dodge(width = 0.6), stat = "identity") + labs(
    title = "Comparing Monthly Substance Users Between States",
    x = "Years",
    y = "Proportion Users to Population (%)",
    fill = "States Compared:"
  ) + 
  theme_bw() +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(limits = c(0, 100) ,breaks = seq(0, 100, 5));

# Attempt to make hovertext informative. Plotly does not handle hovertext well when creating the graph from ggplot
ggplotly(p, tooltip = c('text'))
})

```

-----------------------------------------------------------------------

### Scatter Graph

```{r create_scatter}
# This scatter graph presents a visual interpretation for all fifty states and the estimated total population that uses a specific substance relative to the total population for the given year selected. States with greater populations will be located farther on the right side of the graph and substances with greater estimated users will be located higher on the graph. This should provide users with a method of comparing states to one another relative to their population size.   

# Plotting estimated count of users against population total using plotly
renderPlotly({
saes %>%
  filter(agegrp == input$age_group, 
         outname == input$outcome_choice, 
         pyearnm == input$year_range) %>%
  plot_ly(
  x = ~pop, y = ~est_total*1000,
  # Hover text:
  hoverinfo = 'text',
  text = ~paste("State:", stname, '<br>Total Users:', est_total*1000, '<br>Population:', pop),
  color = ~est_total, size = ~est_total) %>%
  layout(title = "Scatterplot Comparing Users Against Total Population",
         yaxis = list(title = "Estimated User Total"),
         xaxis = list(title = "Population Total "),
         margin = list(b = 100), xaxis = list(tickprefix = " "))
})
```



